services:
  media_server:
    build: .
    image: o2-av-media-server:local
    ports:
      - "8710:8710"
    env_file:
      - .env
    environment:
      REDIS_URI: redis://redis:6379
    restart: unless-stopped
    volumes:
      - ./o2-files:/code/o2-files
    depends_on:
      - redis
    command:
      - uvicorn
      - server:app
      - --host
      - 0.0.0.0
      - --port
      - "8710"
      - --reload
      - --log-level
      - debug
    networks:
      - o2-scheduler_backnet

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - o2-scheduler_backnet

networks:
  o2-scheduler_backnet:
    external: true
